### ISSUE TITLE
DEVELOP should be properly handled by `pip install -e`

### ISSUE THREAD

**Issue by tiberiuichim** [plone/plone-backend#108]
If we assume I have multiple addons specified: 

```
DEVELOP="src/addon1 src/addon2"
```

[then the `pip install -e `](https://github.com/plone/plone-backend/blob/0d06323d45b5e2f0e490330c359b16c884a4663f/skeleton/docker-entrypoint.sh#L116) should be called like:

```
bin/pip install -e src/add1 -e src/addon2
```

**Comment by tiberiuichim** [comment]
A workaround could be to set `DEVELOP="src/addon1 -e src/addon2 -e src/addon3"`

**Comment by davisagli** [comment]
Fixed in https://github.com/plone/plone-backend/pull/107
