### ISSUE TITLE
setuptools version and installation step during installation of Plone

### ISSUE THREAD

**Issue by me-kell** [plone/plone-backend#112]
When creating a `venv` with `python3 -m venv` the packages `pip` and `setuptools` are installed in specific versions (e.g. `pip-20.3.4` and `setuptools-44.1.1`).

The command `/app/bin/pip install -U "pip==${PIP_VERSION}" wheel` updates `pip` to the version specified in `${PIP_VERSION}` and installs `wheel` to the current version (i.e. `pip-22.3.1` and `wheel-0.38.4`) but `setuptools` remains installed (i.e. in version `setuptools-44.1.1`)

This version (i.e. `setuptools-44.1.1`) is used later to build the wheels (e.g. for plone.volto, Chameleon, repoze.xmliter, Zope2, ZODB3, future, sgmllib3k) when installing `Plone` with `/app/bin/pip install Plone ${EXTRA_PACKAGES} -c /app/constraints.txt`.

Only after the wheels are build, the installed version `setuptools-44.1.1` is uninstalled and `setuptools-65.7.0` is installed according to the version specified in `/app/constraints.txt`

Im not sure if there might be any problems when building the wheels with `setuptools` in a differnt version as later installed.

Should that be the case I'd suggest to install `setuptools` in the version specified in `/app/constraints.txt` before installing `Plone`.

Furthermore and since `/app/constraints.txt` already specifies the versions of `pip`, `setuptools`, and `wheel` (i.e. `pip-22.3.1`, `setuptools-65.7.0`, `wheel-0.38.4`) I'd also suggest to update `pip` and installing `wheel` and `setuptools` using `-c /app/constraints.txt`. This would make the use of the variable `${PIP_VERSION}` redundant.

Consider replacing the following [line #18 in Dockerfile.builder](https://github.com/plone/plone-backend/blob/57e30d06a960be9ca818e6b887285e19ab9b0ddb/Dockerfile.builder#L18):

`/app/bin/pip install -U "pip==${PIP_VERSION}" wheel`

with

`/app/bin/pip install -U pip wheel setuptools -c /app/constraints.txt`

and removing the variable declaration `PIP_VERSION=22.3.1` in [line #7 in Dockerfile.builder](https://github.com/plone/plone-backend/blob/57e30d06a960be9ca818e6b887285e19ab9b0ddb/Dockerfile.builder#L7):

**Comment by davisagli** [comment]
This sounds good to me.

**Comment by davisagli** [comment]
This was done in https://github.com/plone/plone-backend/commit/22a00999d6e71ea8b78342ef27d300e5ac538215
