### ISSUE TITLE
Remove env var _PIP_USE_IMPORTLIB_METADATA

### ISSUE THREAD

**Issue by jensens** [plone/plone-backend#139]
`_PIP_USE_IMPORTLIB_METADATA=0` at

https://github.com/plone/plone-backend/blob/416e5177ae29997c985da019b573bd17c0cf2981/Dockerfile#L22C5-L22C32

is no longer needed: we are using the latest pip where this was fixed.

**Comment by fredvd** [comment]
PR here #142
