### ISSUE TITLE
How can I provide a custom zope.ini in an image based on this?

### ISSUE THREAD

**Issue by erral** [plone/plone-backend#154]
The current plone-backend image outputs both the access log and the event log to the stdout and thus when running `docker logs backend` I see both outputs mixed.

I would like to silence the access log, as I already have the access log in the proxy before the backend, and to do so I need to change the provided `zope.ini`.

How can I do when I am using plone-backend as a base image in my project created by cookieplone?

**Comment by davisagli** [comment]
You can add a custom zope.ini to your project repository, and copy it to etc/zope.ini in the backend Dockerfile. This will overwrite the one that is included in the plone-backend image.

**Comment by yurj** [comment]
`docker logs backend > /dev/null 2>/tmp/stderr.log`

for temporary logging. For long time logging, maybe using the syslog driver (`-–log-driver syslog`) and filter out unwanted logs and keep wanted ones based on level can work?

**Comment by erral** [comment]
> You can add a custom zope.ini to your project repository, and copy it to etc/zope.ini in the backend Dockerfile. This will overwrite the one that is included in the plone-backend image.

Thanks! That will definitely work!

**Comment by stevepiercy** [comment]
Would this make a good how-to in https://6.docs.plone.org/admin-guide/configure-zope.html, which also needs to be updated for Cookieplone? Or perhaps under https://6.docs.plone.org/install/containers/index.html#next-steps? This seems like a common usage example to me.
