### ISSUE TITLE
System Upgrade?

### ISSUE THREAD

**Issue by jensens** [plone/plone-backend#22]
I would do an `apt-get upgrade -y` here. Any reason why we don't?
https://github.com/plone/plone-backend/blob/e59d0e91f5ac82e91547764409fbabf97e479b3a/6.0/6.0.0a2/Dockerfile.python39#L9-L11

**Comment by jensens** [comment]
This is an older one, but do we want it? Opinions? @davisagli @ericof

**Comment by ericof** [comment]
No opinions, tbh. We inherit from the Python image, so I trust them to update the image

**Comment by davisagli** [comment]
Ideally we should release updated images with updated OS packages at a regular interval even if there isn't a new Plone release. Hopefully this is the case for our base Python image, but I wouldn't assume.

**Comment by davisagli** [comment]
Currently we do an upgrade:

https://github.com/plone/plone-backend/blob/22a00999d6e71ea8b78342ef27d300e5ac538215/Dockerfile.builder#L29
