### ISSUE TITLE
why using python venv inside container?

### ISSUE THREAD

**Issue by iham** [plone/plone-backend#60]
inside the docker files (standard and nightly) the project is setup as you would in a local dev-environment.

why? the container already gives that level of encapsulation we need.

am I missing a point here?

**Comment by fredvd** [comment]
I think there are at least 3 reasons to always create a venv:

* The container is still a 'mini' os environment where you don't want to pollute the 'container' OS python with application specific python modules.  It's good practise is to minimise and only run 'one' application process, but on startup and whatever subprocesses are run by the plone instance could still use the default Python interpreter. 

* We advise all local/source installs to use a virtualenv, keep the same practise/setup in the container image generation so we test this as often as possible. 

I'm not sure but maybe it also helps to keep the filesystem layers of the image a bit tighter (and controllabe with caching when building the image when all extra installed modules go in their own (venv) directory, but this is more of a wild guess.

**Comment by iham** [comment]
thanks @fredvd 

I understand the idea and won't argue about local dev setups and still see no reason - but that's me :D

btw: I saw this about using venv to pass installed python modules to another docker stage:
https://pythonspeed.com/articles/multi-stage-docker-python/

**Comment by jensens** [comment]
We stick to venv
