### ISSUE TITLE
why use wheels instead of venv?

### ISSUE THREAD

**Issue by iham** [plone/plone-backend#61]
followup to #60 

after investigating deeper into docker multistage I came across the topic of wheels vs venv.
we use both and I would like to understand why.

according to this article [https://pythonspeed.com/articles/multi-stage-docker-python/](https://pythonspeed.com/articles/multi-stage-docker-python/) a venv is perfectly capable of being passed from one stage to the other - as we do using the wheels directory.

this made me lift my eyebrow:

> "Another solution to the problem is to build all the packages as wheels—binary packages with the compiled code—and then copy the wheel files over to the build stage and install them there. This works, but doesn’t really add much."

a second source I found: [https://testdriven.io/blog/docker-best-practices/#using-python-virtual-environments](https://testdriven.io/blog/docker-best-practices/#using-python-virtual-environments) indicates even more concrete:
> "you may want to use a virtual environment in a multi-stage build rather than building wheel files."

is there any other benefit of using wheels over venv?

**Comment by iham** [comment]
to add up to that:

I understand wheels are good - better then eggs.
my research is about what to copy from one docker stage to the other.
the venv (I don't care if there are wheels or eggs installed) or the wheels directory.

the current way - using wheels directory - is doing the ```pip install``` twice.
once to get the packages and then a second time to make them installed in the venv again.

by copying the complete venv (maybe cleaned from .pyc files - and no matter if using eggs or wheels) I don't need to reinstall the binaries, as all is in place and I only need to activate the venv.

**Comment by iham** [comment]
diggin deeper...

installing python packages into a venv already does wheels - so no worries about the wheels.

I just don't see, why to create a wheels-cache, copy that to a new stage and reinstall all using that "cache"

just copying the venv dir including all its wheels and fire it up - no reinstall needed.

**Comment by jensens** [comment]
I agree here, we have no advantages, at least I am aware of. 
I think this could also reduce image size, since `/wheelhouse` still persists in the layer.
