### ISSUE TITLE
Don't use root user when running containers

### ISSUE THREAD

**Issue by davisagli** [plone/plone-backend#62]
It's a best practice to not use the root user in containers (see https://pythonspeed.com/articles/root-capabilities-docker-security/)

This image currently adds a `plone` user but should also set it as the active user with https://docs.docker.com/engine/reference/builder/#user

**Comment by avoinea** [comment]
@davisagli As we have a complex docker-entrypoint that sometimes requires root permissions (e.g.: `chown`) we are using the `gosu` to start plone with the right user. See https://github.com/plone/plone-backend/blob/5.2.x/skeleton/docker-entrypoint.sh#L18

**Comment by avoinea** [comment]
@davisagli See also https://github.com/tianon/gosu#why

**Comment by davisagli** [comment]
@avoinea thanks, it makes more sense now

I'm not sure I agree that creating the data directories and running chown should happen in the entrypoint, but that's another topic...
