### ISSUE TITLE
Cant figure out connecting  the apache solr via plone-backend .

### ISSUE THREAD

**Issue by surajmachamasi** [plone/plone-backend#65]
i have been working connecting apache solr via the plone-backend. i still couldnot  figure it out. most of the examples are using the the buildout.cfg for connecting the solr. thus,  how can we make use of the plone-backed image to integrate apache solr.

**Comment by stevepiercy** [comment]
What did you try?

What did you read?

Did you ask for help on the [Community Forum](https://community.plone.org/)?

You could try this old training: https://training.plone.org/5/solr/index.html

Or searching the Plone 5 docs. Here's the first hit for "solr": https://docs.plone.org/develop/plone/searching_and_indexing/external-catalogs.html

**Comment by surajmachamasi** [comment]
inside the plone-backed container, there is no buildoout.cfg. or is there any alternative way for the plone-backed image to connect the solr?

**Comment by nileshgulia1** [comment]
@surajmachamasi [plone-backend](https://github.com/plone/plone-backend) is pip based installation of Plone hence it doesn't have `buildout.cfg`. The best way is to ask the question in the forum.
