### ISSUE TITLE
having css issue after using tls

### ISSUE THREAD

**Issue by surajmachamasi** [plone/plone-backend#68]
tested the plone backend without tls, All the css is working fine. but after using the tls on the test domain, i am having css issue.  i couldnot figure out the where to  make changes. i couldnot find the env relating to this. 

used image  plone/plone-backend:6.0.0b1

uploaded the screenshot  of the issue. 
![image](https://user-images.githubusercontent.com/84307751/189634456-41665bc9-a01d-4ac5-9f14-81ce140647c5.png)

**Comment by davisagli** [comment]
The gateway that is forwarding traffic to the Plone backend needs to set the `X-Forwarded-Proto` request header to `https` so that the backend knows to generate https URLs.

**Comment by davisagli** [comment]
Closing because this is not an issue but a request for help. https://community.plone.org/ is the best place to ask questions like this.
