### ISSUE TITLE
Invalid URL for README "Extending from this image" in docker entrypoint

### ISSUE THREAD

**Issue by Querela** [plone/plone-backend#84]
When running the backend container an invalid URL is being printed to the console. In 95246aac5657520f88442e6c030059653aedbc86 the whole section about "Extending from this image" was removed.

Maybe, (a) point to the official documentation, or (b) remove the link from the entrypoint script.

https://github.com/plone/plone-backend/blob/6b46109805124c84455e4df515226b4aabbea217/skeleton/docker-entrypoint.sh#L95

**Comment by davisagli** [comment]
@Querela Thanks for pointing that out. Fixed in https://github.com/plone/plone-backend/commit/e6c52898330af11bb8844689c779c446cc511b05
